blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/go-kit/kit/discussions/new?category=q-a
    about: Questions and discussions with the Go kit community

  - name: Website
    url: https://gokit.io/
    about: Project overview, examples, frequently asked questions, etc.

  - name: Reference
    url: https://pkg.go.dev/github.com/go-kit/kit
    about: Go kit package documentation

  - name: Slack channel
    url: https://gophers.slack.com/messages/go-kit
    about: Real-time discussions and Q&A
