name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        run: |
          go test -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1.0.15
        with:
          file: ./coverage.txt
